FROM gradle:jdk17 AS builder

WORKDIR /libs/gateway-service

#COPY gateway-service/gradlew ./gateway-service/gradlew
#COPY gateway-service/gradle ./gateway-service/gradle
#COPY gateway-service/build.gradle ./gateway-service
#COPY gateway-service/settings.gradle ./gateway-service

COPY gateway-service/ .

RUN chmod +x ./gradlew

RUN ./gradlew dependencies --no-daemon || true


COPY core ../core

RUN ./gradlew build --no-daemon -x test

FROM eclipse-temurin:17.0.10_7-jre

WORKDIR /app

COPY --from=builder /libs/gateway-service/build/libs/*.jar app.jar

ENTRYPOINT ["java", "-Dspring.profiles.active=prod", "-jar", "app.jar"]