# 실행할 도커 환경 이미지
FROM gradle:jdk17 AS builder

# 작업을 수행할 가상환경 DIR
# 앞으로 발생하는 모든 명령어는 WorkDIR을 기준으로 작성됨.
WORKDIR /libs

#COPY payment-service/gradlew ./payment-service/gradlew
#COPY payment-service/gradle ./payment-service/gradle
#COPY payment-service/build.gradle ./payment-service
#COPY payment-service/settings.gradle ./payment-service

# 즉 이거는 현재 위치에 있는 payment-service를
# 가상 환경의 /libs에 payment-servic라는 폴더 생성
COPY ./payment-service ./payment-service

# payment-service 내 /gradlew 실행 권한 부여
RUN chmod +x ./payment-service/gradlew

# payment-service내 의존성 추가
RUN ./payment-service/gradlew dependencies --no-daemon || true

# /libs에 core 복사 /libs/core 로 카피
COPY ./core ./core

WORKDIR /libs/payment-service
RUN ./gradlew build --no-daemon -x test

FROM eclipse-temurin:17.0.10_7-jre

WORKDIR /app

COPY --from=builder /libs/payment-service/build/libs/*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]