# 실행할 도커 환경 이미지
FROM gradle:jdk17 AS builder

# 작업을 수행할 가상환경 DIR
# 앞으로 발생하는 모든 명령어는 WorkDIR을 기준으로 작성됨.
WORKDIR /libs

#COPY recommendation-service/gradlew ./recommendation-service/gradlew
#COPY recommendation-service/gradle ./recommendation-service/gradle
#COPY recommendation-service/build.gradle ./recommendation-service
#COPY recommendation-service/settings.gradle ./recommendation-service

# 즉 이거는 현재 위치에 있는 recommendation-service를
# 가상 환경의 /libs에 recommendation-servic라는 폴더 생성
COPY ./recommendation-service ./recommendation-service

# recommendation-service 내 /gradlew 실행 권한 부여
RUN chmod +x ./recommendation-service/gradlew

# recommendation-service내 의존성 추가
RUN ./recommendation-service/gradlew dependencies --no-daemon || true

# /libs에 core 복사 /libs/core 로 카피
COPY ./core ./core

WORKDIR /libs/recommendation-service
RUN ./gradlew build --no-daemon -x test

FROM eclipse-temurin:17.0.10_7-jre

WORKDIR /app

COPY --from=builder /libs/recommendation-service/build/libs/*.jar app.jar
ENTRYPOINT ["java","-Dspring.profiles.active=prod", "-jar", "app.jar"]