# 실행할 도커 환경 이미지
FROM gradle:jdk17 AS builder

# 작업을 수행할 가상환경 DIR
# 앞으로 발생하는 모든 명령어는 WorkDIR을 기준으로 작성됨.
WORKDIR /libs

#COPY search-service/gradlew ./search-service/gradlew
#COPY search-service/gradle ./search-service/gradle
#COPY search-service/build.gradle ./search-service
#COPY search-service/settings.gradle ./search-service

# 즉 이거는 현재 위치에 있는 search-service를
# 가상 환경의 /libs에 search-servic라는 폴더 생성
COPY ./search-service ./search-service

# search-service 내 /gradlew 실행 권한 부여
RUN chmod +x ./search-service/gradlew

# search-service내 의존성 추가
RUN ./search-service/gradlew dependencies --no-daemon || true

# /libs에 core 복사 /libs/core 로 카피
COPY ./core ./core

WORKDIR /libs/search-service
RUN ./gradlew build --no-daemon -x test

FROM eclipse-temurin:17.0.10_7-jre

WORKDIR /app

COPY --from=builder /libs/search-service/build/libs/*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]