# 실행할 도커 환경 이미지
FROM gradle:jdk17 AS builder

# 작업을 수행할 가상환경 DIR
# 앞으로 발생하는 모든 명령어는 WorkDIR을 기준으로 작성됨.
WORKDIR /libs

#COPY member-service/gradlew ./member-service/gradlew
#COPY member-service/gradle ./member-service/gradle
#COPY member-service/build.gradle ./member-service
#COPY member-service/settings.gradle ./member-service

# 즉 이거는 현재 위치에 있는 member-service를
# 가상 환경의 /libs에 member-servic라는 폴더 생성
COPY ./member-service ./member-service

# member-service 내 /gradlew 실행 권한 부여
RUN chmod +x ./member-service/gradlew

# member-service내 의존성 추가
RUN ./member-service/gradlew dependencies --no-daemon || true

# /libs에 core 복사 /libs/core 로 카피
COPY ./core ./core

WORKDIR /libs/member-service
RUN ./gradlew build --no-daemon -x test

FROM eclipse-temurin:17.0.10_7-jre

WORKDIR /app

COPY --from=builder /libs/member-service/build/libs/*.jar app.jar
COPY --from=builder /libs/member-service/src/main/resources/application-prod.yml ./config/
ENTRYPOINT ["java", "-Dspring.profiles.active=prod", "-jar", "app.jar"]