FROM gradle:jdk17 AS builder

WORKDIR /libs/member-service

#COPY member-service/gradlew ./member-service/gradlew
#COPY member-service/gradle ./member-service/gradle
#COPY member-service/build.gradle ./member-service
#COPY member-service/settings.gradle ./member-service

COPY member-service/ .

RUN chmod +x ./gradlew

RUN ./gradlew dependencies --no-daemon || true


COPY core ../core

RUN ./gradlew build --no-daemon -x test

FROM eclipse-temurin:17.0.10_7-jre

WORKDIR /app

COPY --from=builder /libs/member-service/build/libs/*.jar app.jar

ENTRYPOINT ["java", "-Dspring.profiles.active=prod", "-jar", "app.jar"]