FROM gradle:jdk17 AS builder

WORKDIR /libs/contract-service

#COPY contract-service/gradlew ./contract-service/gradlew
#COPY contract-service/gradle ./contract-service/gradle
#COPY contract-service/build.gradle ./contract-service
#COPY contract-service/settings.gradle ./contract-service

COPY contract-service/ .

RUN chmod +x ./gradlew

RUN ./gradlew dependencies --no-daemon || true


COPY core ../core

RUN ./gradlew build --no-daemon -x test

FROM eclipse-temurin:17.0.10_7-jre

WORKDIR /app

COPY --from=builder /libs/contract-service/build/libs/*.jar app.jar

ENTRYPOINT ["java", "-Dspring.profiles.active=prod", "-jar", "app.jar"]