# 실행할 도커 환경 이미지
FROM gradle:jdk17 AS builder

# 작업을 수행할 가상환경 DIR
# 앞으로 발생하는 모든 명령어는 WorkDIR을 기준으로 작성됨.
WORKDIR /libs

#COPY cartpost-service/gradlew ./cartpost-service/gradlew
#COPY cartpost-service/gradle ./cartpost-service/gradle
#COPY cartpost-service/build.gradle ./cartpost-service
#COPY cartpost-service/settings.gradle ./cartpost-service

# 즉 이거는 현재 위치에 있는 cartpost-service를
# 가상 환경의 /libs에 cartpost-servic라는 폴더 생성
COPY ./cartpost-service ./cartpost-service

# cartpost-service 내 /gradlew 실행 권한 부여
RUN chmod +x ./cartpost-service/gradlew

# cartpost-service내 의존성 추가
RUN ./cartpost-service/gradlew dependencies --no-daemon || true

# /libs에 core 복사 /libs/core 로 카피
COPY ./core ./core

WORKDIR /libs/cartpost-service
RUN ./gradlew build --no-daemon -x test

FROM eclipse-temurin:17.0.10_7-jre

WORKDIR /app

COPY --from=builder /libs/cartpost-service/build/libs/*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]