FROM gradle:jdk17 AS builder

WORKDIR /libs/cartpost-service

#COPY cartpost-service/gradlew ./cartpost-service/gradlew
#COPY cartpost-service/gradle ./cartpost-service/gradle
#COPY cartpost-service/build.gradle ./cartpost-service
#COPY cartpost-service/settings.gradle ./cartpost-service

COPY cartpost-service/ .

RUN chmod +x ./gradlew

RUN ./gradlew dependencies --no-daemon || true


COPY core ../core

RUN ./gradlew build --no-daemon -x test

FROM eclipse-temurin:17.0.10_7-jre

WORKDIR /app

COPY --from=builder /libs/cartpost-service/build/libs/*.jar app.jar

ENTRYPOINT ["java", "-Dspring.profiles.active=prod", "-jar", "app.jar"]