
services:
  cartpost-service:
    build:
      context: .
      dockerfile: Dockerfile_cartpost
    image: hexagon-cartpost-service:latest

  communication-service:
    build:
      context: .
      dockerfile: Dockerfile_communication
    image: hexagon-communication-service:latest

  contract-service:
    build:
      context: .
      dockerfile: Dockerfile_contract
    image: hexagon-contract-service:latest

  discovery-service:
    build:
      context: .
      dockerfile: Dockerfile_discovery
    image: hexagon-discovery-service:latest

  gateway-service:
    build:
      context: .
      dockerfile: Dockerfile_gateway
    image: hexagon-gateway-service:latest

  member-service:
    build:
      context: .
      dockerfile: Dockerfile_member
    image: hexagon-member-service:latest

  payment-service:
    build:
      context: .
      dockerfile: Dockerfile_payment
    image: hexagon-payment-service:latest

  profile-service:
    build:
      context: .
      dockerfile: Dockerfile_profile
    image: hexagon-profile-service:latest

  search-service:
    build:
      context: .
      dockerfile: Dockerfile_search
    image: hexagon-search-service:latest