server:
  port: 8084


spring:
  application:
    name: member-service

  jpa:
    open-in-view: false #Lazy Loading 사용 시 트랜잭션 종료를 명확하게 관리하기 위해 false
    hibernate:
      ddl-auto: validate # 음에는 create로 시작하여 엔티티 확인 후 validate로 변경
    properties:
      hibernate:
        show_sql: false
        format_sql: false #쿼리 로그를 보기 쉽게 포맷

  datasource:
    # TODO: 프로젝트 환경에 맞게 DB URL, Username, Password 수정 필요!!
    url: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?rewriteBatchedStatements=true&connectionTimeout=3000&socketTimeout=10000
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  #redis 관련 설정 ( Spring Boot 버전에 따라 spring.redis.haost 일 수도 있음. )
  data:
    redis:
      # 이후 Docker에 올라가면 localhost 대신 redis container 명을 작성해주어야함.
      #host: redis
      host: redis
      port: 6379

  #security 관련 설정
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            scope: account_email #카카오는 이메일을 받아오려면 서비스 검증을 받아야합니다.
            authorization-grant-type: authorization_code
            redirect-uri: ${EC2_DOMAIN}/login/oauth2/code/kakao
            client-name: Kakao
            client-authentication-method: client_secret_post
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            scope: email
            authorization-grant-type: authorization_code
            redirect-uri: ${EC2_DOMAIN}/login/oauth2/code/naver
            client-name: Naver
            client-authentication-method: client_secret_post
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: email
            redirect-uri: ${EC2_DOMAIN}/login/oauth2/code/google
            client-name: Google

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  kafka:
    bootstrap-servers: kafka:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      acks: all

      properties:
        delivery.timeout.ms: 120000
        linger.ms: 0
        request.timeout.ms: 30000
        enable.idempotence: true
        allow.auto.create.topics: true

    consumer:
      group-id: contract-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages:
        allow.auto.create.topics: false

kafka:
  topic:
    member:
      create-topic: member-create-topic
      update-topic: member-update-topic
  config:
    topic-partitions: 1
    topic-replications: 1

jwt:
  access-token:
    secret: ${JWT_ACCESS_SECRET}
    ttl: ${JWT_ACCESS_TTL} # 15분
  refresh-token:
    secret: ${JWT_REFRESH_SECRET}
    ttl: ${JWT_REFRESH_TTL} # 14일

  claims:
    member-code: member-code
    is-sign: is-signed-up

redirect-url:
  login:
    success: ${EC2_DOMAIN}/login/success
    need-signup: ${EC2_DOMAIN}/login/need-signup
    failure: ${EC2_DOMAIN}/login/fail

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    instance-id: "${spring.application.name}:${server.port}:${random.uuid}"
    hostname: hexagon-member-service

springdoc:
  swagger-ui:
    path: /api/members/swagger-ui
  api-docs:
    path: /api/members/v3/api-docs

request:
  uri:
    ratings:
      info: "lb://PROFILE-SERVICE/api/ratings"

