server:
  port: 8000

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webflux:
          routes:
            #region SWAGGER_ROUTES
            - id: cartpost-swagger-ui
              uri: lb://CARTPOST-SERVICE
              predicates:
                - Path=/api/commissions/swagger-ui,/api/commissions/v3/api-docs,/api/commissions/swagger-ui/**,/api/commissions/v3/api-docs/**

            - id: communication-swagger-ui
              uri: lb://COMMUNICATION-SERVICE
              predicates:
                - Path=/api/chatrooms/swagger-ui,/api/chatrooms/v3/api-docs,/api/chatrooms/swagger-ui/**,/api/chatrooms/v3/api-docs/**

            - id: contract-swagger-ui
              uri: lb://CONTRACT-SERVICE
              predicates:
                - Path=/api/contracts/swagger-ui,/api/contracts/v3/api-docs,/api/contracts/swagger-ui/**,/api/contracts/v3/api-docs/**

            - id: member-swagger-ui
              uri: lb://MEMBER-SERVICE
              predicates:
                - Path=/api/members/swagger-ui,/api/members/v3/api-docs,/api/members/swagger-ui/**,/api/members/v3/api-docs/**

            - id: payment-swagger-ui
              uri: lb://PAYMENT-SERVICE
              predicates:
                - Path=/api/payments/swagger-ui,/api/payments/v3/api-docs,/api/payments/swagger-ui/**,/api/payments/v3/api-docs/**

            - id: profile-swagger-ui
              uri: lb://PROFILE-SERVICE
              predicates:
                - Path=/api/profiles/swagger-ui,/api/profiles/v3/api-docs,/api/profiles/swagger-ui/**,/api/profiles/v3/api-docs/**

            - id: search-swagger-ui
              uri: lb://SEARCH-SERVICE
              predicates:
                - Path=/api/search/swagger-ui,/api/search/swagger-ui/**,/api/search/v3/api-docs,/api/search/v3/api-docs/**

            - id: s3-swagger-ui
              uri: lb://s3-service
              predicates:
                - Path=/api/s3/swagger-ui,/api/s3/swagger-ui/**,/api/s3/v3/api-docs,/api/s3/v3/api-docs/**

            ##TODO(이후 ai 서비스 개발 시 변경)
            #            - id: ai-swagger-ui
            #              uri: lb://ai-service
            #              predicates:
            #                - Path=/api/ai/swagger-ui,/api/ai/swagger-ui/**,/api/ai/v3/api-docs,/api/ai/v3/api-docs/**
            #endregion SWAGGER_ROUTES

            #region HEALTH_CHECK_ROUTES
            - id: cartpost-health-check-api
              uri: lb://CARTPOST-SERVICE
              predicates:
                - Path=/api/commissions/connectCheck,/api/commissions/healthCheck

            - id: communication-health-check-api
              uri: lb://COMMUNICATION-SERVICE
              predicates:
                - Path=/api/chatrooms/connectCheck,/api/chatrooms/healthCheck

            - id: contract-health-check-api
              uri: lb://CONTRACT-SERVICE
              predicates:
                - Path=/api/contracts/connectCheck,/api/contracts/healthCheck

            - id: member-health-check-api
              uri: lb://MEMBER-SERVICE
              predicates:
                - Path=/api/members/connectCheck,/api/members/healthCheck

            - id: payment-health-check-api
              uri: lb://PAYMENT-SERVICE
              predicates:
                - Path=/api/payments/connectCheck,/api/payments/healthCheck

            - id: profile-health-check-api
              uri: lb://PROFILE-SERVICE
              predicates:
                - Path=/api/profiles/connectCheck,/api/profiles/healthCheck

            - id: search-health-check-api
              uri: lb://SEARCH-SERVICE
              predicates:
                - Path=/api/search/connectCheck,/api/search/healthCheck
            #endregion HEALTH_CHECK_ROUTES

            #region CARTPOST_SERVICE_ROUTES

            # 아무 자격이 필요 없는 API 요청
            - id: cartpost-service
              uri: lb://CARTPOST-SERVICE
              predicates:
                - Path=/api/commissions/{comissions_code}
                - Method=GET
            - id: cartpost-service-2
              uri: lb://CARTPOST-SERVICE
              predicates:
                - Path=/api/commissions/exist/**
                - Method=GET
              filters:
                - GlobalExceptionHandlingFilter
                - TokenAuthenticationFilter

            # 클라이언트 자격이 필요한 API 요청
            - id: cartpost-service-with-client
              uri: lb://CARTPOST-SERVICE
              predicates:
                - Path=/api/commissions/**,/api/commissions,/api/carts/**
              filters:
                - GlobalExceptionHandlingFilter
                - TokenAuthenticationFilter
                - IsSignCheckFilter
                - IsClientCheckFilter

            #endregion CARTPOST_SERVICE_ROUTES

            #region COMMUNICATION_SERVICE_ROUTES
            - id: communication-service
              uri: lb://COMMUNICATION-SERVICE
              predicates:
                - Path=/ws/chat

            - id: communication-service-need-auth
              uri: lb://COMMUNICATION-SERVICE
              predicates:
                - Path=/api/chatrooms/**,/api/chatrooms
              filters:
                - GlobalExceptionHandlingFilter
                - TokenAuthenticationFilter
                - IsSignCheckFilter

            #endregion COMMUNICATION_SERVICE_ROUTES

            #region CONTRACT_SERVICE_ROUTES
            - id: contract-service-freelancer
              uri: lb://CONTRACT-SERVICE
              predicates:
                - Path=/api/contracts
                - Method=POST
              filters:
                - GlobalExceptionHandlingFilter
                - TokenAuthenticationFilter
                - IsSignCheckFilter
                - IsFreelancerCheckFilter

            - id: contract-service-both
              uri: lb://CONTRACT-SERVICE
              predicates:
                - Path=/api/contracts
                - Method=POST
              filters:
                - GlobalExceptionHandlingFilter
                - TokenAuthenticationFilter
                - IsSignCheckFilter
                - IsFreelancerCheckFilter
                - IsClientCheckFilter

            - id: contract-service
              uri: lb://CONTRACT-SERVICE
              predicates:
                - Path=/api/contracts/**,/api/contracts,/api/deposits/**,/api/deposits
              filters:
                - GlobalExceptionHandlingFilter
                - TokenAuthenticationFilter
                - IsSignCheckFilter

            #endregion CONTRACT_SERVICE_ROUTES

            #region MEMBER_SERVICE_ROUTES

            - id: member-service-no-auth
              uri: lb://MEMBER-SERVICE
              predicates:
                - Path=/api/members
                - Method=GET

            # 회원가입의 경우 IsSign 필요 없음.
            - id: member-service-sign
              uri: lb://MEMBER-SERVICE
              predicates:
                - Path=/api/members
                - Method=POST
              filters:
                - GlobalExceptionHandlingFilter
                - TokenAuthenticationFilter

            # 닉네임 체크의 경우 IsSign 필요 없음(회원가입 때도 쓰이기 떄문에).
            - id: member-service-check-name
              uri: lb://MEMBER-SERVICE
              predicates:
                - Path=/api/members/check-name
                - Method=GET
              filters:
                - GlobalExceptionHandlingFilter
                - TokenAuthenticationFilter

            #######
            # Member SERVICE
            #######
            - id: member-service-need-auth
              uri: lb://MEMBER-SERVICE
              predicates:
                - Path=/api/members,/api/members/**,/api/auth/email/**
              filters:
                - GlobalExceptionHandlingFilter
                - TokenAuthenticationFilter
                - IsSignCheckFilter

            - id: member-service
              uri: lb://MEMBER-SERVICE
              predicates:
                - Path=/oauth2/**,/login/**,/login,/api/auth,/api/auth/**


            #######
            # MEMBER SERVICE - INTERNAL (PROFILE -> MEMBER 통신용)
            #######
            - id: member-service-internal
              uri: lb://MEMBER-SERVICE
              predicates:
                - Path=/internal/members/**

            #endregion MEMBER_SERVICE_ROUTES

            #region PAYMENT_SERVICE_ROUTES

            - id: payment-service
              uri: lb://PAYMENT-SERVICE
              predicates:
                - Path=/api/payments/**,/api/payments
              filters:
                - GlobalExceptionHandlingFilter
                - TokenAuthenticationFilter
                - IsSignCheckFilter
                - IsClientCheckFilter

            #endregion PAYMENT_SERVICE_ROUTES

            #region PROFILE_SERVICE_ROUTES

            #region RESUME_ROUTES
            - id: profile-resumes-read
              uri: lb://PROFILE-SERVICE
              predicates:
                - Path=/api/resumes/{resumeCode}
                - Method=GET
              filters:
                - GlobalExceptionHandlingFilter
                - TokenAuthenticationFilter
                - IsSignCheckFilter

            - id: profile-resumes-freelancer
              uri: lb://PROFILE-SERVICE
              predicates:
                - Path=/api/resumes,/api/resumes/me,/api/resumes/{resumeCode},/api/resumes/{resumeCode}/experiences,/api/resumes/{resumeCode}/experiences/{experienceCode}
              filters:
                - GlobalExceptionHandlingFilter
                - TokenAuthenticationFilter
                - IsSignCheckFilter
                - IsFreelancerCheckFilter
            #endregion RESUME_ROUTES

            #region SELF_PROMOTION_ROUTES
            - id: profile-self-promotions-public
              uri: lb://PROFILE-SERVICE
              predicates:
                - Path=/api/self-promotions,/api/self-promotions/{promotionCode}
                - Method=GET

            - id: profile-self-promotions-isSign
              uri: lb://PROFILE-SERVICE
              predicates:
                - Path=/api/self-promotions
                - Method=POST
              filters:
                - GlobalExceptionHandlingFilter
                - TokenAuthenticationFilter
                - IsSignCheckFilter

            - id: profile-self-promotions-freelancer
              uri: lb://PROFILE-SERVICE
              predicates:
                - Path=/api/self-promotions,/api/self-promotions/{promotionCode},/api/self-promotions/me
              filters:
                - GlobalExceptionHandlingFilter
                - TokenAuthenticationFilter
                - IsSignCheckFilter
                - IsFreelancerCheckFilter
            #endregion SELF_PROMOTION_ROUTES

            #region TAG_ROUTES
            - id: profile-tags-public
              uri: lb://PROFILE-SERVICE
              predicates:
                - Path=/api/tags

            - id: profile-tags-freelancer
              uri: lb://PROFILE-SERVICE
              predicates:
                - Path=/api/tags/{tagCode}/members/me,/api/tags/me,/api/tags/members/me
              filters:
                - GlobalExceptionHandlingFilter
                - TokenAuthenticationFilter
                - IsSignCheckFilter
                - IsFreelancerCheckFilter
            #endregion TAG_ROUTES

            #endregion PROFILE_SERVICE_ROUTES

            #region SEARCH_SERVICE_ROUTES
            - id: search-service
              uri: lb://SEARCH-SERVICE
              predicates:
                - Path=/api/search/**

            #endregion SEARCH_SERVICE_ROUTES

            #region S3_SERVICE_ROUTES
            - id: s3-service
              uri: lb://s3-service
              predicates:
                - Path=/api/s3/**,/api/s3
              filters:
                - GlobalExceptionHandlingFilter
                - TokenAuthenticationFilter
            #endregion S3_SERVICE_ROUTES

            #region AI_SERVICE_ROUTES
            - id: ai-service
              uri: lb://recommendation-service
              predicates:
                - Path=/api/recommendations/**
              filters:
                - GlobalExceptionHandlingFilter
                - TokenAuthenticationFilter
                - IsSignCheckFilter
                - IsClientCheckFilter
            #endregion AI_SERVICE_ROUTES

cors:
  allowed:
    origin: ${CORS_ALLOWED_ORIGIN}

jwt:
  access-token:
    secret: ${JWT_ACCESS_SECRET}
  claims:
    member-code: member-code
    is-sign: is-signed-up
    member-role: role


eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    instance-id: "${spring.application.name}:${server.port}:${random.uuid}"
    hostname: hexagon-gateway-service