server:
  port: 8088

spring:
  application:
    name: s3-service

  datasource:
    url: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?rewriteBatchedStatements=true&connectionTimeout=3000&socketTimeout=10000
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate # or validate / create / create-drop
    properties:
      hibernate:
        format_sql: false
        show_sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    instance-id: "${spring.application.name}:${server.port}:${random.uuid}"
    hostname: hexagon-s3-service

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}