server:
  port: 8089

spring:
  application:
    name: recommendation-service

  datasource:
    # TODO: 프로젝트 환경에 맞게 DB URL, Username, Password 수정 필요!!
    url: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?rewriteBatchedStatements=true&connectionTimeout=3000&socketTimeout=10000
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  ai:
    # retry
    retry:
      max-attempts: 3

    # embedding client
    openai:
      api-key: ${OPEN_AI_API_KEY}
      embedding:
        options:
          model: ${OPENAI_EMBEDDING_MODEL}

    # vector store
    vectorstore:
      pinecone:
        api-key: ${VECTOR_DB_API_KEY}
        index-name: ${INDEX_NAME}

  kafka:
    # kafka cluster
    bootstrap-servers: kafka:9092

    # kafka consumer
    consumer:
      group-id: recommendation-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: org.hexagon.core.*
        spring.json.use.type.headers: true
        allow.auto.create.topics: false

# kafka topic
kafka:
  event:
    topic:
      profile-changed: profile.changed

eureka:
  instance:
    instance-id: "${spring.application.name}:${server.port}:${random.uuid}"
    hostname: hexagon-recommendation-service
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
