plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.7'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
description = 'profile-service'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}

ext {
	set('springCloudVersion', "2025.0.0")
}

dependencies {
    implementation project(':core')

	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa' // JPA
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.5' // Swagger
	implementation 'org.springframework.boot:spring-boot-starter-validation' // Validation
	runtimeOnly 'com.mysql:mysql-connector-j' // MySQL
	implementation 'org.springframework.cloud:spring-cloud-starter-openfeign' // Feign Client
	implementation 'org.springframework.kafka:spring-kafka' // Kafka
	testRuntimeOnly 'com.h2database:h2' // H2 (테스트 시에만 로드)

	// 롬복
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
	}
}

tasks.named('test') {
	useJUnitPlatform()
    systemProperties = System.properties
}
