name: cartpost-service ci/cd

on:
  push:
    branches:
      - test/ci-cd/208-1
    paths:
      - 'cartpost-service/**'

jobs:
  releasing:
    uses: ./.github/workflows/release-workflow.yml
    secrets: inherit
    permissions:
      contents: write
      attestations: write
      packages: write
      id-token: write
    with:
      service-name: hexagon-cartpost-service
      service-dir: ./cartpost-service
      file-name: Dockerfile_cartpost

  deploying:
    needs: releasing
    uses: ./.github/workflows/deploy-workflow.yml
    secrets: inherit
    with:
      service-name: hexagon-cartpost-service
      image-tag: ${{ needs.releasing.outputs.tag_name }}
