name: CI Test Script

#이벤트의 종류
on:
  # 특정 원격지 레포지토리의 어떤 이벤트가 발생했을때
  push:
    ## 어떤 브랜치로 발생했을 때
    branches:
      - test/ci-cd/132

# 해당 job을 순서대로 실행하겠다.
# 해당 jobs는 파이프라인 형태로 작동함.
    # 입력으로 들어와서 출력이 나가는게 다음 파이프의 입력으로 들어감
    # 잡은 병렬적으로 실행 될 수 있지만 파이프라인으로 구성되게 할 수 있음.
jobs:
  # 해당 잡의 key
  ## application.yml 들 실행
  # cartpost yml 생성 로직
  code-test:
    name: 코드 테스트
    # Action은 job 실행시 가상 환경을 이용함, 그래서 원래는 요금이 듬
    # 한달의 2000분 정도.
    # 그래서 해당 프로젝트에서는 4팀이 같이 쓰니까 action을 간략화 해두었음.
    runs-on: ubuntu-latest

    steps:
      - name: 브랜치로 체크아웃
        # 메인브랜치로 이동
        uses: actions/checkout@v5

      #java가 없기 때문에 java를 설치해줘야함.
      - name: JDK 세팅
        uses: actions/setup-java@v5
        with:
          # java 버전과 벤더를 설정해줘야함
          java-version: '17'
          distribution: 'temurin'

      - name: CARTPOST yml 생성
        run: |
          mkdir -p ./cartpost-service/src/main/resources
          echo '${{ vars.TEST_YML }}' > ./cartpost-service/src/main/resources/application.yml

      - name: COMMUNICATION yml 생성
        run: |
          mkdir -p ./communication-service/src/main/resources
          echo '${{ vars.TEST_YML }}' > ./communication-service/src/main/resources/application.yml

      - name: CONTRACT yml 생성
        run: |
          mkdir -p ./contract-service/src/main/resources
          echo '${{ vars.TEST_YML }}' > ./contract-service/src/main/resources/application.yml

      - name: DISCOVERY yml 생성
        run: |
          mkdir -p ./discovery-service/src/main/resources
          echo '${{ vars.TEST_YML }}' > ./discovery-service/src/main/resources/application.yml

      - name: GATEWAY yml 생성
        run: |
          mkdir -p ./gateway-service/src/main/resources
          echo '${{ vars.TEST_YML }}' > ./gateway-service/src/main/resources/application.yml

      - name: MEMBER yml 생성
        run: |
          mkdir -p ./member-service/src/main/resources
          echo '${{ vars.TEST_YML }}' > ./member-service/src/main/resources/application.yml

      - name: PAYMENT yml 생성
        run: |
          mkdir -p ./payment-service/src/main/resources
          echo '${{ vars.TEST_YML }}' > ./payment-service/src/main/resources/application.yml

      - name: PROFILE yml 생성
        run: |
          mkdir -p ./profile-service/src/main/resources
          echo '${{ vars.TEST_YML }}' > ./profile-service/src/main/resources/application.yml

      - name: SEARCH yml 생성
        run: |
          mkdir -p ./search-service/src/main/resources
          echo '${{ vars.TEST_YML }}' > ./search-service/src/main/resources/application.yml

      - name: 전체 모듈 gradlew 권한 세팅
        run: |
          chmod +x ./cartpost-service/gradlew
          chmod +x ./communication-service/gradlew
          chmod +x ./contract-service/gradlew
          chmod +x ./discovery-service/gradlew
          chmod +x ./gateway-service/gradlew
          chmod +x ./member-service/gradlew
          chmod +x ./payment-service/gradlew
          chmod +x ./profile-service/gradlew
          chmod +x ./search-service/gradlew

      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      - name: Run Kafka container and wait for ready
        run: |
          docker run -d \
            --name kafka \
            -p 9092:9092 \
            -p 9091:9091 \
            -p 9090:9090 \
            -e KAFKA_NODE_ID=1 \
            -e CLUSTER_ID=ZWU1Y2JiNDctNDg3ZC4tNGY2Ny1iNzJh \
            -e KAFKA_PROCESS_ROLES=controller,broker \
            -e KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9091 \
            -e KAFKA_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9092 \
            -e KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9090,EXTERNAL://localhost:9092 \
            -e KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT \
            -e KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER \
            -e KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT \
            -e KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1 \
            -e KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1 \
            -e KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1 \
            apache/kafka

      - name: Elasticsearch docker run
        run: |
          docker run -d \
            --name elasticsearch \
            -p 9200:9200 \
            -e node.name=es01 \
            -e cluster.name=cluster-exp \
            -e discovery.type=single-node \
            -e xpack.security.enabled=false \
            -e xpack.security.http.ssl.enabled=false \
            -e ES_JAVA_OPTS="-Xms512m -Xmx512m" \
            eddie1031/es:9.1.3


      - name: Wait for Elasticsearch to be up
        run: |
          for i in {1..10}; do
            if curl -sSf http://localhost:9200; then
              echo "Elasticsearch is up"
              break
            fi
            echo "Waiting for Elasticsearch..."
            sleep 8
          done

      - name: application.yml 파일 내용 확인
        run: cat ./search-service/src/main/resources/application.yml

      - name: search-service 테스트 실행
        working-directory: ./search-service
        run: ./gradlew test -i --no-daemon

      - name: Elasticsearch docker down
        run: |
          docker stop elasticsearch
          docker rm elasticsearch

      - name: Redis docker run
        run: |
          docker run -d \
            --name redis \
            -p 6379:6379 \
            redis:7

      - name: Wait for Redis to be up
        run: |
          for i in {1..10}; do
            if docker exec redis redis-cli ping | grep -q PONG; then
              echo "Redis is up"
              break
            fi
            echo "Waiting for Redis..."
            sleep 2
          done

      - name: member-service 테스트 실행
        working-directory: ./member-service
        run: ./gradlew test -i --no-daemon

      - name: contract-service 테스트 실행
        working-directory: ./contract-service
        run: ./gradlew test -i --no-daemon

      - name: cartpost-service 테스트 실행
        working-directory: ./cartpost-service
        run: ./gradlew test -i --no-daemon

      - name: communication-service 테스트 실행
        working-directory: ./communication-service
        run: ./gradlew test -i --no-daemon

      - name: payment-service 테스트 실행
        working-directory: ./payment-service
        run: ./gradlew test -i --no-daemon

      - name: profile-service 테스트 실행
        working-directory: ./profile-service
        run: ./gradlew test -i --no-daemon

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-report
          path: "**/build/reports/tests/test"
