name: discovery-service ci/cd

on:
  push:
    branches:
      - test/ci-cd/225
    paths:
      - 'discovery-service/**'

jobs:

  releasing:
    uses: ./.github/workflows/release-workflow.yml
    secrets: inherit
    permissions:
      contents: write
      attestations: write
      packages: write
      id-token: write
    with:
      service-name: hexagon-discovery-service
      service-dir: ./discovery-service
      file-name: Dockerfile_discovery

  deploying:
    needs: releasing
    uses: ./.github/workflows/deploy-workflow.yml
    secrets: inherit
    with:
      service-name: hexagon-discovery-service
      image-tag: ${{ needs.releasing.outputs.tag_name }}
