name: recommendation-service ci/cd

on:
  push:
    branches:
      - main
    paths:
      - 'recommendation-service/**'

jobs:

  releasing:
    uses: ./.github/workflows/release-workflow.yml
    secrets: inherit
    permissions:
      contents: write
      attestations: write
      packages: write
      id-token: write
    with:
      service-name: hexagon-recommendation-service
      service-dir: ./recommendation-service
      file-name: Dockerfile_recommendation

  deploying:
    needs: releasing
    uses: ./.github/workflows/deploy-workflow.yml
    secrets: inherit
    with:
      service-name: hexagon-recommendation-service
      image-tag: ${{ needs.releasing.outputs.tag_name }}
