name: Build and release docker image

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
      service-dir:
        required: true
        type: string
      file-name:
        required: true
        type: string
    outputs:
      tag_name:
        value: ${{ jobs.tagging.outputs.tag_name }}




env:
  REGISTRY: docker.io

jobs:

  tagging:
    name: 태깅 및 릴리즈
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.tag_version.outputs.new_tag }}
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5
#
#      - name: versioning and tagging
#        id: tag_version
#        uses: mathieudutour/github-tag-action@v6.2
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          fetch_all_tags: 'true'
      - name: versioning and tagging
        id: tag_version
        run: |
          RAND=$(openssl rand -base64 16)
          echo "random_string=$RAND" >> $GITHUB_OUTPUT

      - name: releasing
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

  build-image:
    name: 도커 이미지 빌드
    runs-on: ubuntu-latest
    needs: tagging

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Check out Repository
        uses: actions/checkout@v5

      - name: ${{ inputs.service-dir }} yml 생성
        run: |
          mkdir -p ${{ inputs.service-dir }}/src/main/resources
          if [[ "${{ inputs.service-dir }}" == *"gateway"* ]]; then
          echo '${{ vars.GATEWAY_YML }}' > ${{ inputs.service-dir }}/src/main/resources/application.yml
          elif [[ "${{ inputs.service-dir }}" == *"cartpost"* ]]; then
          echo '${{ vars.CARTPOST_YML }}' > ${{ inputs.service-dir }}/src/main/resources/application.yml
          elif [[ "${{ inputs.service-dir }}" == *"communication"* ]]; then
          echo '${{ vars.COMMUNICATION_YML }}' > ${{ inputs.service-dir }}/src/main/resources/application.yml
          elif [[ "${{ inputs.service-dir }}" == *"contract"* ]]; then
          echo '${{ vars.CONTRACT_YML }}' > ${{ inputs.service-dir }}/src/main/resources/application.yml
          elif [[ "${{ inputs.service-dir }}" == *"discovery"* ]]; then
          echo '${{ vars.DISCOVERY_YML }}' > ${{ inputs.service-dir }}/src/main/resources/application.yml
          elif [[ "${{ inputs.service-dir }}" == *"member"* ]]; then
          echo '${{ vars.MEMBER_YML }}' > ${{ inputs.service-dir }}/src/main/resources/application.yml
          elif [[ "${{ inputs.service-dir }}" == *"payment"* ]]; then
          echo '${{ vars.PAYMENT_YML }}' > ${{ inputs.service-dir }}/src/main/resources/application.yml
          elif [[ "${{ inputs.service-dir }}" == *"profile"* ]]; then
          echo '${{ vars.PROFILE_YML }}' > ${{ inputs.service-dir }}/src/main/resources/application.yml
          elif [[ "${{ inputs.service-dir }}" == *"search"* ]]; then
          echo '${{ vars.SEARCH_YML }}' > ${{ inputs.service-dir }}/src/main/resources/application.yml
          else
          echo "알 수 없는 서비스입니다."
          fi

      - name: Sign in github container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_AC_KEY }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ inputs.service-name }}
          tags: |
            type=sha
            type=raw,value=${{ needs.tagging.outputs.tag_name }}
            type=raw,value=latest

      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./${{ inputs.file-name }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

